### PR TITLE
T22279: Also uninstall autodelete extensions

### PR DESCRIPTION
**Pull request by smspillaz**
This is a follow-up to #189 

If an extension is marked autodelete, we should remove it when the source flatpak gets uninstalled.

### CODE REVIEW

**Comment by smspillaz** [comment]
Currently stacked on #189

**Comment by smspillaz** [comment]
Will need to be rebased once #189 is merged.

**Comment by pwithnall** [comment]
> Will need to be rebased once #189 is merged

It’s merged; this can be rebased.

**Comment by smspillaz** [comment]
(Do we want this anymore? If not, we should close this)

**Comment by pwithnall** [comment]
> (Do we want this anymore? If not, we should close this)

I think the conclusion so far from https://phabricator.endlessm.com/T22279 is that we might want this, but it should be discussed upstream first, since the behaviour of `flatpak uninstall` might need to change as well. That discussion hasn’t happened yet.

I’ve rebased this on `master` as of today (trivial rebase), just so it’s obvious what code hasn’t been merged here. Let’s close this PR but keep the branch in place until the discussion has happened on the task (which I don’t think has a particularly high priority at the moment).

**Pull request closed without merging**
