### PR TITLE
T22054 Allow installing dependencies from remotes without a locally configured collection ID

### PR DESCRIPTION
**Pull request by pwithnall**
https://phabricator.endlessm.com/T22054

### CODE REVIEW

**Comment by smspillaz** [comment]
LGTM apart from the one comment

**Comment by smspillaz** [comment]
FWIW: This is a CR Pass from me (not sure if we were still blocking on that)

**Comment by rshuler** [comment]
retest this please

**Comment by rshuler** [comment]
retest this please

**Comment by smspillaz** [comment]
Last two commits are 👍

**Pull request merged**
