### PR TITLE
T27723 Fix GTimeVal deprecation warnings

### PR DESCRIPTION
**Pull request by pwithnall**
https://phabricator.endlessm.com/T27723

### CODE REVIEW

**Comment by mwleeds** [comment]
Looks like the jenkins build fails because we only have glib 2.61.3:
```
The following packages have unmet dependencies:
 builddeps:/build : Depends: libglib2.0-dev (>= 2.62.0) but 2.61.3+dev16.56ea7e8-0bem1 is to be installed
```

**Comment by pwithnall** [comment]
bot, retest this please

**Comment by pwithnall** [comment]
The updated GLib has landed, and I’ve fixed a few more warnings in this branch, so it needs re-reviewing.

**Comment by mwleeds** [comment]
Unfortunate that we're adding so much boilerplate code, but LGTM

**Pull request merged**
