### PR TITLE
T20876: Add test for invalid entry as "serial" number

### PR DESCRIPTION
**Pull request by smspillaz**
https://phabricator.endlessm.com/T20876

### CODE REVIEW

**Comment by smspillaz** [comment]
Good point. I'll add such a test now.

**Comment by pwithnall** [comment]
This looks good to me, but needs rebasing to avoid the conflicts.

**Comment by smspillaz** [comment]
Yeah, that second commit was obviated by 0711a9088f145394d9e19cbf85be280254ac15fb . Rebased.

**Comment by pwithnall** [comment]
Jenkins checks passed. Merging.

**Pull request merged**
