### PR TITLE
debian: Sort .install files alphabetically

### PR DESCRIPTION
**Pull request by pwithnall**
Using `sort`.

Signed-off-by: Philip Withnall <withnall@endlessm.com>

---

It was one of the review comments from an earlier T16682 patch review.

### CODE REVIEW

**Comment by smspillaz** [comment]
Yup, we were in need of this.

**Comment by pwithnall** [comment]
> Yup, we were in need of this.

Do you want to accept and merge it then? The [Jenkins failure is spurious](https://phabricator.endlessm.com/T2254#523469).

**Comment by pwithnall** [comment]
Jenkins, retest this please

**Comment by dbnicholson** [comment]
really retest this please

**Pull request merged**
